### ISSUE TITLE
Can not load eeg ckpt

### ISSUE THREAD

**Issue by fredfyyang** [TencentARC/ViT-Lens#13]
Hi, I just want to load the eeg ckpt from your huggingface repo but it seems that tons of keys are not matched. Any chance can you double check on your side if it can be loaded successful?

**Comment by StanLei52** [comment]
Hi, thanks for your question. I will double-check on my side. Could you please provide details on the script you used for loading the eeg ckpt?

**Comment by StanLei52** [comment]
It turns out the script do not load model from hf ckpt correctly. I've fixed this bug. You may pull the latest code and retry running. Thanks!
