### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by ShuvenduRoy** [TencentARC/ViT-Lens#16]
Hi, 

Thanks for releasing this great project! 

I realized that the file `audioset_unbalanced_train.json` required for training the audio model is missing. Could you please share this file or let me know how to acquire this.

**Comment by StanLei52** [comment]
Hi,

I've uploaded our copy to [release](https://github.com/TencentARC/ViT-Lens/releases/download/vitlens.release.v0.1.0/audioset_unbalanced_train.json). 

To make your own copy, you may download the videos from the list of [audioset](https://research.google.com/audioset/download.html), and then trim the video and audio according to the annotated timestamps. To enrich the captions, you may refer to [CLAP](https://github.com/LAION-AI/CLAP) for their used captions.

**Comment by ShuvenduRoy** [comment]
Great. Thanks!
