### ISSUE TITLE
Training code or training parameter configurations

### ISSUE THREAD

**Issue by yifliu3** [TencentARC/ViT-Lens#3]
Hi,

I'm very insterested in your great work and am trying to train your model on my own data. As this repo currently solely contains the inference code, I'm wondering if you can share your training part, or share the training parameter configuration, especially the parameters of the perceiver. Thanks a lot!

**Comment by StanLei52** [comment]
Thank you for your interest in our work. We will release the code for training in the near future.

If you wish to proceed with implementation on your own, you can refer to the configurations of the perceiver in our inference example as a reference.

**Comment by StanLei52** [comment]
Hi @yifliu3, the training code has been released. Feel free to re-open this issue if there is any question.
