### ISSUE TITLE
Training Time and GPU usages

### ISSUE THREAD

**Issue by haoranD** [TencentARC/ViT-Lens#7]
Hi,

Thanks for the exceptional work you have presented. It is truly remarkable and contributes significantly to the field.

After reviewing your paper, I noted the mention of experiments being conducted on 32GB V100 GPU clusters. However,  can you please give more details of the resources utilized for this project? Could you kindly provide information on the total training time and the exact number of GPUs employed during this period?

Thanks a lot.

**Comment by StanLei52** [comment]
Hi there,

Thank you for your interest. Please refer to [TRAIN_INFERENCE.md](https://github.com/TencentARC/ViT-Lens/blob/main/TRAIN_INFERENCE.md) and click the training items for details. Note that you may use less GPUs by setting `--accum-freq`, and it may lead to a different training time compared to our experiments. If you require further details on other model variants, feel free to reach out.

**Comment by haoranD** [comment]
Thanks for your kind reply, it is quite helpful.

May ask when the code for integration with InstructBLIP and SEED will be released?

**Comment by haoranD** [comment]
Thanks for your kind reply, it is quite helpful.

May I ask when the code for integration with InstructBLIP and SEED will be released?

**Comment by StanLei52** [comment]
Due to limited bandwidth, I will aim to release these parts within one month.

**Comment by haoranD** [comment]
Thanks
