### ISSUE TITLE
Something about Training Methodologies and Experimental Approaches for Video Data

### ISSUE THREAD

**Issue by cyChen2003** [TencentARC/ViT-Lens#8]
I'm thoroughly impressed with your project and I'm eager to apply the model to my video data.  However, the current TRAIN_INFERENCE.md does not provide the relevant usage information. Could you kindly publish the associated training methodologies or experimental approaches? Your assistance would be greatly appreciated.  Thank you!

**Comment by StanLei52** [comment]
Hi, thank you very much for your interest. 

As mentioned in our paper, we followed ImageBind's setup to ensure fair comparison. Therefore, we did not train ViT-Lens on video data, but followed ImageBind to use the CLIP-ViT to aggregate frame(image) representations for a video clip, and fuse it with the corresponding audio representation (trained by ViT-Lens). You may find this in the [ImageBind paper](https://arxiv.org/pdf/2305.05665.pdf) Appendix C. I will allocate time in the future to clean and upload this section of the code.
